### ISSUE TITLE
Please Add GridPlus

### ISSUE THREAD

**Issue by MidnightOnMars** [ethereum-cat-herders/1559-outreach#1]
GridPlus fully supports this proposal and is prepared to promptly implement all required wallet changes.

**Comment by timbeiko** [comment]
@MidnightOnMars can you open a quick PR against the `README` and I'll merge it? Thanks!

**Comment by MidnightOnMars** [comment]
Forking now to open the PR - I blame Trent's tweet telling us to open an issue to be added!  ;)

**Comment by timbeiko** [comment]
Oops, that's my bad! suggested a PR because it can be done in the Github UI easily, @MidnightOnMars :-) I'll let you do this one, and if future requests come in via issues I can just add them myself.
