### ISSUE TITLE
handle.fi SUPPORTS EIP-1559

### ISSUE THREAD

**Issue by seahound** [ethereum-cat-herders/1559-outreach#11]
handle.fi: multi currency stablecoins backed by ethereum supports the EIP-1559 proposal

**Comment by timbeiko** [comment]
@seahound are you the owner of the project? If not, do you have a link to share which shows their support? Thanks!

**Comment by seahound** [comment]
Yes @timbeiko I am a core contributor to the project! What further would you like to see? Thnks & Rgds

**Comment by timbeiko** [comment]
That's good! I will add it now.

**Comment by timbeiko** [comment]
Closing, see: https://github.com/ethereum-cat-herders/1559-outreach/commit/6b51d44218b8364557f308306731d1f7b081a289
