### ISSUE TITLE
reality.eth

### ISSUE THREAD

**Issue by edmundedgar** [ethereum-cat-herders/1559-outreach#4]
Oppose. 

Because of the way it's been sold we'll likely be lumbered with this as a long-term monetary policy in PoS, where it doesn't have the effects that people with PoW on their minds think it will. It's bad to design your monetary policy as an implementation detail of a UX change.

For PoW, support conditional on miner support. It's reckless to do this against miner opposition, as the gas market depends on the operation of levers controlled by miners.

**Comment by tvanepps** [comment]
Is this project still active?

**Comment by edmundedgar** [comment]
Certainly is. Not much usage on mainnet now because of gas prices but we're deployed on xdai, the most well-known project it's powering right now would be Omen.

**Comment by tvanepps** [comment]
gotcha, thanks for the color. will add
